### ISSUE TITLE
Axios Error Error: Request failed with status code 400

### ISSUE THREAD

**Issue by softwarecrash** [Patrick-Walther/ioBroker.pvforecast#3]
i have tested the adapter, it runs fine for the first time, but now i become tthis error, any idea what goes wrong?

`

pvforecast.0 | 2021-06-14 09:10:00.013 | debug | (28431) 2021-06-14 09:10
-- | -- | -- | --
pvforecast.0 | 2021-06-14 09:09:52.957 | error | (28431) Axios Error Error: Request failed with status code 400
pvforecast.0 | 2021-06-14 09:09:52.512 | info | (28431) ThisUrl https://api.forecast.solar/estimate/xx.xxx/xx.xxx/33/195/1.380
pvforecast.0 | 2021-06-14 09:09:52.511 | debug | (28431) Link: https://api.forecast.solar/estimate/xx.xxx/xx.xxx/33/195/1.380
pvforecast.0 | 2021-06-14 09:09:52.510 | debug | (28431) Account public gewählt
pvforecast.0 | 2021-06-14 09:09:52.510 | debug | (28431) setting-gps-iobroker:  undefined
pvforecast.0 | 2021-06-14 09:09:52.509 | debug | (28431)
pvforecast.0 | 2021-06-14 09:09:52.509 | debug | (28431) Account: account-public
pvforecast.0 | 2021-06-14 09:09:52.508 | debug | (28431) plant name: XXXX
pvforecast.0 | 2021-06-14 09:09:52.508 | debug | (28431) Link: https://api.forecast.solar
pvforecast.0 | 2021-06-14 09:09:52.507 | debug | (28431) Plant-performance: 1.380
pvforecast.0 | 2021-06-14 09:09:52.507 | debug | (28431) Azimuth: 195
pvforecast.0 | 2021-06-14 09:09:52.506 | debug | (28431) Neigung: 33
pvforecast.0 | 2021-06-14 09:09:52.505 | debug | (28431) Breitengrad: 51.03079495599263
pvforecast.0 | 2021-06-14 09:09:52.505 | debug | (28431) Längengrad: 11.535322666168211
pvforecast.0 | 2021-06-14 09:09:52.504 | debug | (28431)
pvforecast.0 | 2021-06-14 09:09:52.461 | info | (28431) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.pvforecast, node: v14.17.0, js-controller: 3.2.16

`

**Comment by Patrick-Walther** [comment]
hi

you have a azimuth  which is not in the range between  -180 .. 180

**Comment by softwarecrash** [comment]
Ah damn, my Foul. Thanks
