### ISSUE TITLE
[Feature Request] Neuer Datenpunkt  - Ertrag von morgen

### ISSUE THREAD

**Issue by Steff42** [Patrick-Walther/ioBroker.pvforecast#4]
Hi,
ich habe gerade deinen Adapter installiert, nachdem ich einige Zeit mit dem Script aus dem ioBroker Forum experimentiert habe.
Und schon hätte ich einen Wunsch. Es gibt ja den Datenpunkt power_day_kWh, kannst Du noch einen weiteren Datenpunkt anlegen in dem der Wert vom morgigen Tage eingetragen wird? Im Script wurde der zu erwartende Ertrag von morgen ja in einem separaten Datenpunkt ausgegeben, wäre super wenn das mit dem Adapter auch gehen würden.

Gruß Steffen

**Comment by Patrick-Walther** [comment]
Hallo,

ist erledigt.

Grüße
