### ISSUE TITLE
[Feature request] Ertragsvorhersage zusätzlich zur JSON-Tabelle in einzelnen Datenpunkten pro Stundeninervall 

### ISSUE THREAD

**Issue by bastian-mer** [Patrick-Walther/ioBroker.pvforecast#6]
Zusätzlich zur Auflistung der Ertragsprognose in einer JSON-Tabelle Darstellung der Prognose in einzelnen Datenpunkten für jedes Stundenintervall:

0-1: 0kwh
1-2: 0kwh
2-3: 0kwh
usw.

**Comment by Patrick-Walther** [comment]
Kannst du das genauer Definieren, stehe gerade auf dem Schlauch.

**Comment by bastian-mer** [comment]
[http://www.bastian-m.de/tmp/iobroker/forum-github/211208.png](http://www.bastian-m.de/tmp/iobroker/forum-github/211208.png)

Ich dachte an sowas wie einen Unterordner "forecast-today", "forecast-tomorrow" etc. in der Objektliste in dem für jedes Zeitintervall (ja nach Abo 15,30 oder 60min) ein eigener State mit der prognostizierten Erzeugungsmenge existiert. (In meinem Beispiel-Screenshot also schonmal für 0-1 Uhr, 0-2 Uhr usw.). Wie auch immer man das dann schlau benannt, wenn z.B. das Abo mit Werten für alle 15min hat. Wahrscheinlich macht grundsätzlich einfach 01, 02, 03, 04 Sinn bzw ggf. 01-00, 01-15, 01-30, 01-45, 02, 02-15

P.S.: Ich finde weder in deinem Github- noch deinem IoBroker-Forumsprofil einen Donate-Link.

**Comment by Patrick-Walther** [comment]
Ist fertig, bitte Testen!

**Comment by bastian-mer** [comment]
Habe gerade einen Testlauf mit meinem API-Key für Daten alle 15min gestartet - scheint zu funktionieren, die States sehen korrekt aus!

**Comment by Patrick-Walther** [comment]
Hab noch zwei Fehler gefunden. Update kommt die Tage.
