### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [Patrick-Walther/ioBroker.pvforecast#8]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/Patrick-Walther/ioBroker.pvforecast

- [x] [E144] common.installedFrom field found in io-package.json. Must be removed.
- [x] [E200] Not found on npm. Please publish
- [x] [E504] found setInterval in "main.js, but no clearInterval detected
- [x] [E300] Not found on travis. Please setup travis
- [x] #10
- [x] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Patrick Walther <walther-patrick@gmx.net>" at the start of LICENSE

I have also found warnings that may be fixed if possible.

- [x] [W113] Adapter should support compact mode
- [x] [W400] Cannot find "pvforecast" in latest repository
- [x] [W801] .npmignore not found
- [x] [W901] .gitignore not found

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.

**Comment by klein0r** [comment]
@mcm1957 Do you know why the checker generates comments on very old (and closed) issues?

**Comment by klein0r** [comment]
Okay danke! Hatte mich nur gewundert, weil ich Notifications vom ioBrokerChecker in ~8 geschlossenen Issues hatte.
